[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"

[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=UTF-8"

[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200
